receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins: ["http://localhost:5173"]
  otelarrow:
    protocols:
      grpc:
        endpoint: "localhost:9002"

exporters:
  otelarrow:
    compression: none
    endpoint: "localhost:9002"
    tls:
      insecure: true

service:
  pipelines:
    traces/main:
      receivers: [otlp]
      exporters: [otelarrow]
